DROP TABLE PUBLIC.USERS IF EXISTS CASCADE;
CREATE TABLE PUBLIC.USERS (
	ID INTEGER IDENTITY,
	USERNAME VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(30) NOT NULL
);
DROP TABLE PUBLIC.FEEDS IF EXISTS CASCADE;
CREATE TABLE PUBLIC.FEEDS (
	ID INTEGER IDENTITY,
	URL VARCHAR(255) NOT NULL
);
DROP TABLE PUBLIC.FEEDUSER IF EXISTS CASCADE;
CREATE TABLE PUBLIC.FEEDUSER (
	ID INTEGER IDENTITY,
	FEEDID INTEGER NOT NULL,
	USERID INTEGER NOT NULL
);
DROP TABLE PUBLIC.ARTICLES IF EXISTS CASCADE;
CREATE TABLE PUBLIC.ARTICLES (
	ID INTEGER IDENTITY,
	FEEDID INTEGER NOT NULL,
	TITLE VARCHAR(255),
	GUID VARCHAR(255) NOT NULL,
	LINK VARCHAR(255),
	DESCRIPTION VARCHAR(255),
	PUBDATE BIGINT
);
DROP TABLE PUBLIC.ARTICLE_STATE IF EXISTS CASCADE;
CREATE TABLE PUBLIC.ARTICLE_STATE (
	ID INTEGER IDENTITY,
	USERID INTEGER NOT NULL,
	FEEDID INTEGER NOT NULL,
	ARTICLEID INTEGER NOT NULL,
	ISREAD BOOLEAN DEFAULT FALSE NOT NULL
);
